language: bash
dist: focal
addons:
  apt:
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
        key_url: 'https://download.docker.com/linux/debian/gpg'
    packages:
      - docker-ce
      - docker-compose
      - shellcheck
      - curl
before_install:
  - sudo git clone https://github.com/bats-core/bats-core.git /opt/bats
  - sudo /opt/bats/install.sh /usr/local
install:
  - sudo docker build -t traefikjam .
script:
  - shellcheck -x ./traefikjam.sh
  - sudo /usr/local/bin/bats ./test/test.bats
