name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run shellcheck
        run: |
          shellcheck $GITHUB_WORKSPACE/traefikjam-functions.sh
          shellcheck -x $GITHUB_WORKSPACE/traefikjam.sh
          
      - name: Build the test image
        run: docker build --tag traefikjam_test --file $GITHUB_WORKSPACE/test/containers/traefikjam_test/Dockerfile  $GITHUB_WORKSPACE
      
      - name: Deploy the non-swarm environment
        run: docker-compose -f $GITHUB_WORKSPACE/test/docker-compose.yml up -d

      - name: Test the non-swarm environment
        run: |
          docker exec traefikjam_test bats /opt/traefikjam/test/test-dind.bats
          docker-compose -f $GITHUB_WORKSPACE/test/docker-compose.yml down
